/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  type Handlers = {
    'HealthCheck': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { status: string; timestamp: string; service: string; version: string }>, never>
    'ChatApi': ApiRouteHandler<{ message: string; conversationId?: string }, ApiResponse<200, { conversationId: string; title: string; explanation: string }> | ApiResponse<500, { conversationId: string; title: string; explanation: string }>, never>
  }
}